export const CITIES_IN_NIGERIA = [
  {
    label: "From anywhere",
    value: "",
  },
  {
    label: "Aba, Abia",
    value: "Aba",
    city: "Aba",
    state: "Abia",
  },
  {
    label: "Umuahia, Abia",
    value: "Umuahia",
    city: "Umuahia",
    state: "Abia",
  },
  {
    label: "Mubi, Adamawa",
    value: "Mubi",
    city: "Mubi",
    state: "Adamawa",
  },
  {
    label: "Yola, Adamawa",
    value: "Yola",
    city: "Yola",
    state: "Adamawa",
  },
  {
    label: "Ikot Ekpene, Akwa Ibom",
    value: "Ikot Ekpene",
    city: "Ikot Ekpene",
    state: "Akwa Ibom",
  },
  {
    label: "Uyo, Akwa Ibom",
    value: "Uyo",
    city: "Uyo",
    state: "Akwa Ibom",
  },
  {
    label: "Awka, Anambra",
    value: "Awka",
    city: "Awka",
    state: "Anambra",
  },
  {
    label: "Onitsha, Anambra",
    value: "Onitsha",
    city: "Onitsha",
    state: "Anambra",
  },
  {
    label: "Azare, Bauchi",
    value: "Azare",
    city: "Azare",
    state: "Bauchi",
  },
  {
    label: "Bauchi, Bauchi",
    value: "Bauchi",
    city: "Bauchi",
    state: "Bauchi",
  },
  {
    label: "Brass, Bayelsa",
    value: "Brass",
    city: "Brass",
    state: "Bayelsa",
  },
  {
    label: "Yenagoa, Bayelsa",
    value: "Yenagoa",
    city: "Yenagoa",
    state: "Bayelsa",
  },
  {
    label: "Gboko, Benue",
    value: "Gboko",
    city: "Gboko",
    state: "Benue",
  },
  {
    label: "Makurdi, Benue",
    value: "Makurdi",
    city: "Makurdi",
    state: "Benue",
  },
  {
    label: "Biu, Borno",
    value: "Biu",
    city: "Biu",
    state: "Borno",
  },
  {
    label: "Maiduguri, Borno",
    value: "Maiduguri",
    city: "Maiduguri",
    state: "Borno",
  },
  {
    label: "Calabar, Cross River",
    value: "Calabar",
    city: "Calabar",
    state: "Cross River",
  },
  {
    label: "Ogoja, Cross River",
    value: "Ogoja",
    city: "Ogoja",
    state: "Cross River",
  },
  {
    label: "Asaba, Delta",
    value: "Asaba",
    city: "Asaba",
    state: "Delta",
  },
  {
    label: "Warri, Delta",
    value: "Warri",
    city: "Warri",
    state: "Delta",
  },
  {
    label: "Abakaliki, Ebonyi",
    value: "Abakaliki",
    city: "Abakaliki",
    state: "Ebonyi",
  },
  {
    label: "Afikpo, Ebonyi",
    value: "Afikpo",
    city: "Afikpo",
    state: "Ebonyi",
  },
  {
    label: "Benin City, Edo",
    value: "Benin City",
    city: "Benin City",
    state: "Edo",
  },
  {
    label: "Ado Ekiti, Ekiti",
    value: "Ado Ekiti",
    city: "Ado Ekiti",
    state: "Ekiti",
  },
  {
    label: "Ijero, Ekiti",
    value: "Ijero",
    city: "Ijero",
    state: "Ekiti",
  },
  {
    label: "Enugu, Enugu",
    value: "Enugu",
    city: "Enugu",
    state: "Enugu",
  },
  {
    label: "Nsukka, Enugu",
    value: "Nsukka",
    city: "Nsukka",
    state: "Enugu",
  },
  {
    label: "Abuja, Federal Capital Territory",
    value: "Abuja",
    city: "Abuja",
    state: "Federal Capital Territory",
  },
  {
    label: "Gombe, Gombe",
    value: "Gombe",
    city: "Gombe",
    state: "Gombe",
  },
  {
    label: "Owerri, Imo",
    value: "Owerri",
    city: "Owerri",
    state: "Imo",
  },
  {
    label: "Dutse, Jigawa",
    value: "Dutse",
    city: "Dutse",
    state: "Jigawa",
  },
  {
    label: "Hadejia, Jigawa",
    value: "Hadejia",
    city: "Hadejia",
    state: "Jigawa",
  },
  {
    label: "Kaduna, Kaduna",
    value: "Kaduna",
    city: "Kaduna",
    state: "Kaduna",
  },
  {
    label: "Zaria, Kaduna",
    value: "Zaria",
    city: "Zaria",
    state: "Kaduna",
  },
  {
    label: "Kano, Kano",
    value: "Kano",
    city: "Kano",
    state: "Kano",
  },
  {
    label: "Daura, Katsina",
    value: "Daura",
    city: "Daura",
    state: "Katsina",
  },
  {
    label: "Katsina, Katsina",
    value: "Katsina",
    city: "Katsina",
    state: "Katsina",
  },
  {
    label: "Birnin Kebbi, Kebbi",
    value: "Birnin Kebbi",
    city: "Birnin Kebbi",
    state: "Kebbi",
  },
  {
    label: "Yelwa, Kebbi",
    value: "Yelwa",
    city: "Yelwa",
    state: "Kebbi",
  },
  {
    label: "Lokoja, Kogi",
    value: "Lokoja",
    city: "Lokoja",
    state: "Kogi",
  },
  {
    label: "Okene, Kogi",
    value: "Okene",
    city: "Okene",
    state: "Kogi",
  },
  {
    label: "Ilorin, Kwara",
    value: "Ilorin",
    city: "Ilorin",
    state: "Kwara",
  },
  {
    label: "Offa, Kwara",
    value: "Offa",
    city: "Offa",
    state: "Kwara",
  },
  {
    label: "Ikeja, Lagos",
    value: "Ikeja",
    city: "Ikeja",
    state: "Lagos",
  },
  {
    label: "Ikorodu, Lagos",
    value: "Ikorodu",
    city: "Ikorodu",
    state: "Lagos",
  },
  {
    label: "Lagos, Lagos",
    value: "Lagos",
    city: "Lagos",
    state: "Lagos",
  },
  {
    label: "Keffi, Nasarawa",
    value: "Keffi",
    city: "Keffi",
    state: "Nasarawa",
  },
  {
    label: "Lafia, Nasarawa",
    value: "Lafia",
    city: "Lafia",
    state: "Nasarawa",
  },
  {
    label: "Minna, Niger",
    value: "Minna",
    city: "Minna",
    state: "Niger",
  },
  {
    label: "Suleja, Niger",
    value: "Suleja",
    city: "Suleja",
    state: "Niger",
  },
  {
    label: "Abeokuta, Ogun",
    value: "Abeokuta",
    city: "Abeokuta",
    state: "Ogun",
  },
  {
    label: "Ijebu Ode, Ogun",
    value: "Ijebu Ode",
    city: "Ijebu Ode",
    state: "Ogun",
  },
  {
    label: "Akure, Ondo",
    value: "Akure",
    city: "Akure",
    state: "Ondo",
  },
  {
    label: "Owo, Ondo",
    value: "Owo",
    city: "Owo",
    state: "Ondo",
  },
  {
    label: "Ilesa, Osun",
    value: "Ilesa",
    city: "Ilesa",
    state: "Osun",
  },
  {
    label: "Osogbo, Osun",
    value: "Osogbo",
    city: "Osogbo",
    state: "Osun",
  },
  {
    label: "Ibadan, Oyo",
    value: "Ibadan",
    city: "Ibadan",
    state: "Oyo",
  },
  {
    label: "Ogbomosho, Oyo",
    value: "Ogbomosho",
    city: "Ogbomosho",
    state: "Oyo",
  },
  {
    label: "Bukuru, Plateau",
    value: "Bukuru",
    city: "Bukuru",
    state: "Plateau",
  },
  {
    label: "Jos, Plateau",
    value: "Jos",
    city: "Jos",
    state: "Plateau",
  },
  {
    label: "Degema, Rivers",
    value: "Degema",
    city: "Degema",
    state: "Rivers",
  },
  {
    label: "Port Harcourt, Rivers",
    value: "Port Harcourt",
    city: "Port Harcourt",
    state: "Rivers",
  },
  {
    label: "Sokoto, Sokoto",
    value: "Sokoto",
    city: "Sokoto",
    state: "Sokoto",
  },
  {
    label: "Jalingo, Taraba",
    value: "Jalingo",
    city: "Jalingo",
    state: "Taraba",
  },
  {
    label: "Damaturu, Yobe",
    value: "Damaturu",
    city: "Damaturu",
    state: "Yobe",
  },
  {
    label: "Potiskum, Yobe",
    value: "Potiskum",
    city: "Potiskum",
    state: "Yobe",
  },
  {
    label: "Gusau, Zamfara",
    value: "Gusau",
    city: "Gusau",
    state: "Zamfara",
  },
];
